M48
; DRILL file KiCad 10.0.1 date 2026-05-13T00:36:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-13T00:36:56-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X60.88Y-96.65
X72.31Y-96.65
T2
X53.75Y-99.0
X53.75Y-162.75
X141.75Y-99.0
X141.75Y-162.75
M30
